### ISSUE TITLE
Possible 10.0 regression

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#134]
Had a report from a user not getting ``10.0.1`` to work, but is able to run ``9.99.82``

Console error screenshots attached, though they don't seem to me to help much.

@synthtech Any idea what it could be?

Tampermonkey, Chrome, macOS

**Comment by synthtech** [comment]
Yea, none of the errors come from Automail.

I installed 10.0.1 with Tampermonkey on Chromium 99.0.4800.0, Edge 97.0.1072.62, and Brave 1.34.80 (Windows 10).
Logged in, browsed some pages and it seemed fine.

Having the specific browser version, their Automail settings, and what pages it doesn't work on would be helpful.

Otherwise, without any other details I could only suggest:
- Updating browser
- Disabling MAL-sync
- Disabling other Anilist userscripts/extensions

**Comment by hohMiyazawa** [comment]
![Uploading image.png…]()

**Comment by hohMiyazawa** [comment]
Which is unfortunately undoubtably an automail error.

I have requested more details, but haven't gotten a reply yet.

**Comment by hohMiyazawa** [comment]
@synthtech Solved, was Chrome version 80.0.3987.149

So it was an issue with private methods in classes not being supported.

I'll advice not using that for compatibility reasons, since it's not an essential feature.

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/09e4ecb91cd7eb462c788f46c529017a46c98790
