### ISSUE TITLE
Suggestions for some new features.

### ISSUE THREAD

**Issue by Tempest32** [hohMiyazawa/Automail#15]
I don't know if I'm allowed to request new features in the "issues" panel, so please let me know about that.

**1. Improvements in anime list filter.**

- Add the year range option as seen in "Browse". Currently you can only select a specific year.

- Allow filtering by tags as well as genres, the advanced tag filtering from browse would be even better

- Allow selecting Hentai in the genre filter.

- Allow selecting multiple formats instead of just one at a time.

- Sorting by episode count. 

**2. Improvements in stats** 

- Display the weighted score. Genres & Tags are sorted by weighted score but you can't see what that score exactly is.

- Extend sorting by weighted score to VA, Studio and Staff stats. 

- Allow VA and Staff list entries to be expanded like the other stat categories. 

**3. Sorting options in studio pages**

Currently the studio pages are sorted by newest first with no options to sort otherwise. 

**4. Option to hide currently watching hentai from the "Anime in progress" section on the homepage.**
***
As an aside, is the release here any different from the one on greasyfork?
Since that was updated on Dec 11th, while the github release was uploaded on Dec 20th

**Comment by hohMiyazawa** [comment]
This is exactly what the issues are for.

As for your entire "Improvements in anime list filter" section, these features can't be added as extensions to the native implementation, so they require *replacing the entire anime list with a script replica*.

That means you are probably not going to get these immediately, but if I (or someone else?) spend the initial effort, these will all be easy to implement.

Weighted Genre and Tag score can use a better implementation. Will get to that.
Same for VA and staff.

Expanding VA and staff may be a bit difficult, due to the way Anilist presents data. But it's possible at some level, so a minor rewrite should in theory be good enough.

3 is relatively easy.

4 should be easy, at least for the custom "in progress" section the script has.

There's no significant  difference between the 20th December release and the Greasyfork release. That week only had a few commits.

**Comment by hohMiyazawa** [comment]
"Allow selecting Hentai in the genre filter." I found a way to implement this in browse. Will be bundled with the hentai card renderer in v9.14

**Comment by hohMiyazawa** [comment]
Never mind, changes incoming.

**Comment by hohMiyazawa** [comment]
3 was implemented a couple of months ago.

**Comment by teeol** [comment]
In Low bandwidth mode, could the Block stuff in the home feed features be applied here? Not seeing Planning and Dropping would be helpful
