### ISSUE TITLE
Implication of "identifiable header per plugin for API requests"

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#167]
> Must use a uniquely identifiable header per plugin for API requests.

This showed up in the new Anilist site rules. It sounds sus.
What are the technical implications of this, regarding the situation of the script?

**Comment by kazzarin** [comment]
Well it's odd this is included as part of the site guidelines instead of mandated in the [API terms of use](https://anilist.gitbook.io/anilist-apiv2-docs/overview/overview). I would just ignore it unless they message you requesting to include it or something.

If it does become mandatory, it should be trivial to change the `User-Agent` or whatever special header they require for api requests.

**Comment by hohMiyazawa** [comment]
@kazzarin Yeah, there's probably nothing that needs to be done immediately, at least not before any clarifications have been posted.

I'm slightly worried though, so what do you think about [this](https://github.com/hohMiyazawa/Automail/commit/2d923f74a97d5f3a0478ae69b9fc8b98864db60f)? It's a backup solution of sorts.

**Comment by kazzarin** [comment]
I suppose that works if the app gets revoked.

**Comment by hohMiyazawa** [comment]
Since nothing has happened, presumably nothing needs to be done
