### ISSUE TITLE
Translation hooks into the list editor?

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#206]
This is a major component that can not yet be translated.

Is there a performant way to hook into it? Presumably a setTimeout/setInterval loop at low frequency would be okay, but it doesn't feel elegant.

**Comment by nategasm** [comment]
Would that be similar to how the hook is done in the rangeSetter module?
If so, I would agree with it not being elegant. It wastes cycles running the callback when nothing is happening.

A nicer solution would be to use a MutationObserver so the callback only happens when something updates on the page (like opening the editor), as opposed to every x milliseconds. It is similar to what https://github.com/hohMiyazawa/Automail/pull/204 is trying to achieve. This would waste less cycles overall and have a faster response time when the editor is opened.

If you're worried about the observer being connected too early you could also use it in combination with a setTimeout so that the observer is only connected after the base nodes have appeared (like .activity-feed or .lists).

**Comment by hohMiyazawa** [comment]
@nategasm Thinking about it, a MutationObserver is actually the perfect solution here. The list editor only appears in one (or a couple?) of places, so a something with ``childList: true`` and ``subTree: false`` would be very performant.

**Comment by nategasm** [comment]
Yeh so something like this will work on all pages. 

```	
	function(){
  		let checker = function(){
		let node = document.querySelector("#app");
			if(!node){
				console.log("setTimeout")
				setTimeout(checker,200);
				return
			}
		}
		checker();
		let mutationConfig = {
			attributes: false,
			childList: true,
			subtree: false
		};
		let observer = new MutationObserver(function(){
			console.log("Mutation Triggered")
			let editor = document.querySelector(".list-editor");
			if(editor){
				console.log("List editor opened")
			}
			else{
				console.log("List editor closed")
			}
		});
		observer.observe(document.querySelector("#app"),mutationConfig)
	}
```
You can actually open the editor from almost anywhere on the site except forums. ie. home and user feeds, user lists, media and even browse pages.
For me the callback here doesn't get triggered on page loads and feed updates, but does on opening/closing the list editor.

**Comment by hohMiyazawa** [comment]
Since the script a few places summons the list editor itself with ``document.getElementById("app").__vue__.$store.dispatch("medialistEditor/open",mediaID)``, I think one must assume that the list editor could appear on any page.

**Comment by hohMiyazawa** [comment]
Done.

https://github.com/hohMiyazawa/Automail/commit/9761de4df6186764cbee3f47747df6b52e726d2b
