### ISSUE TITLE
Site-wide Custom CSS Support

### ISSUE THREAD

**Issue by dizzyatlovich** [hohMiyazawa/Automail#37]
It seems that if I switch to, for example, Home tab before Custom CSS is loaded on the profile, the CSS will be loaded into Home tab instead. I replicated this several times, and it seems that if I switch to Home tab at the right moment (after the CSS started initialization but before it is injected), I can get it to work.

So a question arises, naturally. Is it possible to implement site-wide Custom CSS support? While I understand that this might not be a desired feature, it might prove to be very useful considering how many people complain about the look of certain parts of AniList.

[Screenshot](https://imgur.com/BSa1Yio)

**Comment by hohMiyazawa** [comment]
You can add site-wide CSS, in the alias field on the settings page https://anilist.co/settings/apps
The syntax is "css/", followed by any css after the slash.

As for the injection you mention, it's undesirable since it applies to other users of the script, who may not be pleased to have the site look altered after visiting your profile page.
