### ISSUE TITLE
Problem with more stats feature when trying it on my own profile.

### ISSUE THREAD

**Issue by Repulles** [hohMiyazawa/Automail#49]
I have a problem with this "more stats" feature in stats:
https://i.imgur.com/fFRSvdC.png

As you can see in the screenshot "More stats" feature shows
"loading anime list...
loading manga list..."

and it's only when i do this on my own profile while im logged in.
When i do this on other people's profiles everything is fine.
When i do this on my own profile but while not logged in it's also fine.

Any solution?

**Comment by hohMiyazawa** [comment]
This has two causes:

1) Persistent storage is disabled in your browser (it's enabled by default). Automail uses that for cache.
2) The stats portion of the script blindly trusts cache to be available.

The second point has been fixed in v9.98, though disabling storage is likely to give you other problems. At the very least, it makes things slower since the script has to request API data every time.

But at least the stats should work now.

**Comment by 1234abcdcba4321** [comment]
I also have this problem (i'm pretty sure firefox addons auto-update to latest? and i've barely touched my firefox settings and there's nothing excluded from cookies and cache).
When logged in, and on my own profile only, it sometimes does not even let me click on "more stats" or "genres and tags" (hard refreshing usually fixes this), and when it does, often nothing on them actually loads (except the stuff in "various statistics" when prompted). The lists in the tag stats pages also often don't load.

**Comment by hohMiyazawa** [comment]
@1234abcdcba4321 The latest Firefox addon is currently older than this thread, so it does not have any of the changes made.
I will get around to update it sometime soon.
