### ISSUE TITLE
Fix for Youtube fullscreen option

### ISSUE THREAD

**Issue by OfficialBispo** [hohMiyazawa/Automail#53]
I was checking the problem about the option "Enable fullscreen button on Youtube videos" not working. 
After a bit of fiddling around with the iframe, I found out that the attribute `__idm_frm__` was causing the attribute `allowfullscreen` to not work.

So, removing that tag works but weirdly, the Youtube link needs to refresh so that the fullscreen button works. One simple way is changing the URL parameter `autohide` from `1` to `0`. I'm not even sure if this parameter is being used for anything, changing that value doesn't alter the video behavior.

Adding these two lines where you set the `allowfullscreen` tag does the job:
```
video.removeAttribute("__idm_frm__");
video.setAttribute("src",video.getAttribute("src").replace("autohide=1","autohide=0"));
```

**Comment by hohMiyazawa** [comment]
Looking up ``__idm_frm__``, it appears to be some weird custom browser thingy, so I'm not touching that unless there's some documentation about what it's actually for.

As for why the fullscreen option fails, I think it's dependens on wheter the youtube embed scripts runs before or after Automail, so your fix is probably just making sure the embed runs again after Automail has changed the tags.

I don't think those parameters actually do anything either, but I will try using the "autoplay" one and set it to "0", since these links really shouldn't be trying to request autoplay in any case.

**Comment by hohMiyazawa** [comment]
Nevermind, that seems to add an extra step of clicking "play"...

**Comment by hohMiyazawa** [comment]
The autohide version seems to work fine. Will test it for a few days before adding it to a release.

**Comment by hohMiyazawa** [comment]
Seems to work fine.
