### ISSUE TITLE
Syntax error on line 16

### ISSUE THREAD

**Issue by ashennedante** [hohMiyazawa/Automail#64]
Hey, I'm trying to download it and I'm getting an error with the code 800A03EA, in line 16 and in character 1. Is it just me? Did I do anything wrong? How can I solve it? Thank you so much!

**Comment by hohMiyazawa** [comment]
A line number isn't much to go from, but I will see.

Which browser and userscript manager are you using?

**Comment by ashennedante** [comment]
I'm using Chrome and GitHub. But I'm totally new to it, maybe I've done something wrong, really.
Here's a screenshot of the issue, it's in Spanish and I translated it above but maybe it can be useful somehow. 
Thank you again so so much.
![image](https://user-images.githubusercontent.com/82117167/113920765-833c3c80-97e5-11eb-990a-811b7c998928.png)

**Comment by hohMiyazawa** [comment]
Ah, the problem is that you don't have a **userscript manager**, a browser addon which is used to run scripts like this one. (Popular ones are Greasemonkey, Tampermonkey and Violentmonkey).

If you go to the install page, https://greasyfork.org/en/scripts/370473-automail, there's a big "?" question mark besides the install button. It has a guide for getting started with userscripts.

**Comment by ashennedante** [comment]
Just did it and it works perfectly fine! Thank you so much for putting with my utter inability haha
